### ISSUE TITLE
code enhancement 

### ISSUE THREAD

**Issue by ybadr99** [akezeth/Portfolio-setup-and-mobile-first#10]
- the logo should be hidden on the navbar menu mobile version
- fonts should be strict like the original design 
- the h1 heading in just 2 lines in the mobile version

**Comment by akezeth** [comment]
Thanks, @Yousef Mohamed for your kind feedback. According to your feedback:
- Changed the h1 heading from 3 lines to just 2 lines in the mobile version.
![image](https://user-images.githubusercontent.com/116703083/231107584-926482bb-264b-4f4b-8e39-b542cdffff6d.png)
- Added additional Google fonts so that the fonts match the original design.
![image](https://user-images.githubusercontent.com/116703083/231106970-34bf2e3d-13c7-407e-bb90-88e339d8f403.png)
- I have changed the logo's visibility to a hidden state on the mobile navbar menu.
![image](https://user-images.githubusercontent.com/116703083/231107915-e9473e9c-af54-4bc8-b668-89ccd254e380.png)
